### ISSUE TITLE
can not play if video dont have audio

### ISSUE THREAD

**Issue by lenhatvu** [SuRGeoNix/MediaRouter#3]
Hi,

Seem your project cannot play if video don't have audio stream.
Please check

**Comment by lenhatvu** [comment]
if disable setup audio, it works fine:
![image](https://user-images.githubusercontent.com/59004953/87141761-c193e200-c2cd-11ea-8422-d3ad0aee7833.png)

**Comment by SuRGeoNix** [comment]
I can play video streams without audio streams properly, can you send a screenshot from vlc Tools -> Codec information? or if you have a sample video so i can reproduce the problem?

**Comment by lenhatvu** [comment]
That stream is from IP camera.
![image](https://user-images.githubusercontent.com/59004953/87144081-66fc8500-c2d1-11ea-837f-b3c4a1672c1c.png)

**Comment by SuRGeoNix** [comment]
It seems that an Audio Stream exists but it's faulty. Not sure if MediaRouter should continue in this case. But you could handle this by catching the ret Error and just set the hasAudio = false and continue, eg:-

if (ret < 0 && ret != ffmpeg.AVERROR_STREAM_NOT_FOUND) hasAudio = false;

If you feel that there is still an issue there, feel free to re-open it!

**Comment by lenhatvu** [comment]
Hi,

ret = SetupStream(AVMediaType.AVMEDIA_TYPE_AUDIO); always success and ret = 0.
This is video, you can try
[20200710_174406.zip](https://github.com/SuRGeoNix/MediaRouter/files/4902647/20200710_174406.zip)

**Comment by SuRGeoNix** [comment]
That seems to be a different issue, probably with demuxing or a codec issue. I'm planning to upgrade ffmpeg.cs in v1.3 with a better configuration for format contexts / codecs which i think will handle this kind of issues better.

My guess, is that issue with matroska (avi/mkv) format and because I use different format contexts for each media steam cannot handle properly the relationship (matroska tables) between streams. I tried to parse video stream as related to audio stream but didn't currently work:-

if      (mType == AVMediaType.AVMEDIA_TYPE_AUDIO)   { streamIndex = ffmpeg.av_find_best_stream(aFmtCtx, mType, -1, vStream->index, null, 0); }

So, I am afraid that this issue cannot be fixed until the ffmpeg.cs re-coding :(

**Comment by SuRGeoNix** [comment]
OK, with further review found the issue. The audio stream even if exists has not frames at all and the Screamer will wait until it will fill the queue at least with AUDIO_MIN_QUEUE_SIZE forever so the following should fix the issue

```
// Fill Queues at least with Min
while (isPlaying && vFrames.Count < VIDEO_MIX_QUEUE_SIZE || (decoder.hasAudio && aFrames.Count < AUDIO_MIX_QUEUE_SIZE && !decoder.isAudioFinish) || (decoder.hasSubs && sFrames.Count < SUBS_MIN_QUEUE_SIZE && !decoder.isSubsFinish ) ) 
     Thread.Sleep(20);
```

**Comment by lenhatvu** [comment]
Thanks
