### ISSUE TITLE
CPU high when video finished

### ISSUE THREAD

**Issue by lenhatvu** [SuRGeoNix/MediaRouter#4]
Hi,

When playing video, CPU around 0.3 % but when video finished, CPU usage raise to 17%.

**Comment by SuRGeoNix** [comment]
I cannot reproduce the issue, can you send more details?

**Comment by lenhatvu** [comment]
I am using video in #3 and modified code as you advise
snapshot when video playing: 
![image](https://user-images.githubusercontent.com/59004953/87237963-c9b36500-c426-11ea-92ff-a590456427bd.png)
snapshot when video finished:
![image](https://user-images.githubusercontent.com/59004953/87237969-ecde1480-c426-11ea-90b2-9497472ed068.png)

**Comment by SuRGeoNix** [comment]
Yes, I see. The problem is that I still can't reproduce the issue on my system (I tried the same media file). Does it happens for any file for you or just that one? Just to make sure, update also to the latest commit and try again. If it happens again try to pause the debugger and see if it loops forever somewhere. I will try to have a better look later on.

**Comment by lenhatvu** [comment]
Hi,

May be problem because i add some option to read rtsp stream ỏ change something. Original your code is ok.

**Comment by SuRGeoNix** [comment]
No problem. Currently for rtsp to avoid the delay you might want to pass an initial parameter to disable Audio/Subs so it will not delay to open format contexts for them as well.
