### ISSUE TITLE
Delay when play live stream

### ISSUE THREAD

**Issue by lenhatvu** [SuRGeoNix/MediaRouter#5]
Hi,

when play rtsp stream from camera, MediaRouter delay 15 seconds compare with VideoPlayer_HWAcceleration in Tutorials folder.
![image](https://user-images.githubusercontent.com/59004953/87214429-a1f4cc00-c356-11ea-9635-a915535306fb.png)

left is MediaRouter, right is VideoPlayer_HWAcceleration
this is rtsp url if you want to test: rtsp://admin:Admin12345@118.70.129.7:24554/Src/mediainput/stream_1

**Comment by SuRGeoNix** [comment]
To be honest, I have never use it for anything else rather files and torrents. But, yes that is seems to be the issue that I mention to you at the other issue. Is because I use 3 different Format Contexts for each stream (Audio/Video/Subtitles). So, it will open the rtsp stream 3 times and that's why the delay. I'm planning to fix this at v1.3 with ffmpeg.cs re-coding.

**Comment by lenhatvu** [comment]
New version no delay.
by add this option, your project can play rtsp stream.
AVDictionary* opts = null;
            ffmpeg.av_dict_set_int(&opts, "rw_timeout", 15000, 0);
            ffmpeg.av_dict_set_int(&opts, "tcp_nodelay", 1, 0);
            ffmpeg.av_dict_set_int(&opts, "stimeout", 15000, 0);
            ffmpeg.av_dict_set(&opts, "rtsp_transport", "tcp", 0);
            ffmpeg.av_dict_set(&opts, "rtsp_flags", "prefer_tcp", 0);
            ffmpeg.av_dict_set_int(&opts, "buffer_size", 2000000, 0);

ret     = ffmpeg.avformat_open_input(&fmtCtxPtr, url, null, &opts);
